name: Urls
values:
  - key: baseUrl
    value: ''
  - key: proxyUrl
    value: ''
  - key: userControllerUrl
    value: ''
  - key: scheduleControllerUrl
    value: ''
  - key: paymentControllerUrl
    value: ''
  - key: bookingControllerUrl
    value: ''
  - key: fullProxyUrl
    value: ''
