// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://apache.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/management/cache": {
            "delete": {
                "description": "Удаляет все записи из кеша в памяти",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache-Management"
                ],
                "summary": "Очистить кеш",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/cache_setting/{id}": {
            "get": {
                "description": "Возвращает настройки кеша для указанного ObjectID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache-Management"
                ],
                "summary": "Получить настройки кеша по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID настройки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/cache_settings/purge": {
            "delete": {
                "description": "Удаляет все настройки кеша для совпадений по началу пути (например, /api/users. Удалит в том числе /api/users/uuid)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache-Management"
                ],
                "summary": "Удалить настройки кеша по началу пути",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Путь для удаления настроек",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/cache_settings/{id}": {
            "delete": {
                "description": "Удаляет настройку кеша для указанного ObjectID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache-Management"
                ],
                "summary": "Удалить настройку кеша по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID настройки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/reload": {
            "get": {
                "description": "Обновляет актуальные правила IP",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IP Management"
                ],
                "summary": "Подгрузить правила IP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/rules": {
            "get": {
                "description": "Возвращает список всех правил IP",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IP-Management"
                ],
                "summary": "Получить все правила IP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.IPRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новый IP в черный, белый или серый список",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IP Management"
                ],
                "summary": "Добавить правило IP",
                "parameters": [
                    {
                        "description": "Данные правила",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.IPRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/management/rules/{id}": {
            "delete": {
                "description": "Удаляет запись из MongoDB по её ObjectID",
                "tags": [
                    "IP-Management"
                ],
                "summary": "Удалить правило IP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID правила",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.IPRule": {
            "type": "object",
            "properties": {
                "burst": {
                    "description": "максимальный всплеск",
                    "type": "integer"
                },
                "comment": {
                    "description": "Для чего это правило (необязательно, но полезно)",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "network": {
                    "description": "Например: \"192.168.1.0/24\"",
                    "type": "string"
                },
                "rate": {
                    "description": "количество запросов в секунду",
                    "type": "number"
                },
                "type": {
                    "description": "\"white\", \"black\", \"grey\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/api/proxy",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Пример сервера для документации",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
