// Code generated by MockGen. DO NOT EDIT.
// Source: cache_repo.go
//
// Generated by this command:
//
//	mockgen -source=cache_repo.go -destination=mocks/mock_cache_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "fitness-proxy/internal/model"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockCacheRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockCacheRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockCacheRepository)(nil).DeleteByID), ctx, id)
}

// DeleteByPath mocks base method.
func (m *MockCacheRepository) DeleteByPath(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPath", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPath indicates an expected call of DeleteByPath.
func (mr *MockCacheRepositoryMockRecorder) DeleteByPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPath", reflect.TypeOf((*MockCacheRepository)(nil).DeleteByPath), ctx, path)
}

// GetByID mocks base method.
func (m *MockCacheRepository) GetByID(ctx context.Context, id string) (*model.CacheSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.CacheSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCacheRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCacheRepository)(nil).GetByID), ctx, id)
}

// GetSettings mocks base method.
func (m *MockCacheRepository) GetSettings(ctx context.Context) ([]model.CacheSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx)
	ret0, _ := ret[0].([]model.CacheSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockCacheRepositoryMockRecorder) GetSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockCacheRepository)(nil).GetSettings), ctx)
}

// GetTTLForPath mocks base method.
func (m *MockCacheRepository) GetTTLForPath(ctx context.Context, path string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTLForPath", ctx, path)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTLForPath indicates an expected call of GetTTLForPath.
func (mr *MockCacheRepositoryMockRecorder) GetTTLForPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTLForPath", reflect.TypeOf((*MockCacheRepository)(nil).GetTTLForPath), ctx, path)
}

// UpdateTTL mocks base method.
func (m *MockCacheRepository) UpdateTTL(ctx context.Context, id primitive.ObjectID, ttl int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTTL", ctx, id, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTTL indicates an expected call of UpdateTTL.
func (mr *MockCacheRepositoryMockRecorder) UpdateTTL(ctx, id, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTTL", reflect.TypeOf((*MockCacheRepository)(nil).UpdateTTL), ctx, id, ttl)
}
