// Code generated by MockGen. DO NOT EDIT.
// Source: ip_rules.go
//
// Generated by this command:
//
//	mockgen -source=ip_rules.go -destination=mocks/mock_ip_rules.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "fitness-proxy/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPRepository is a mock of IPRepository interface.
type MockIPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPRepositoryMockRecorder
	isgomock struct{}
}

// MockIPRepositoryMockRecorder is the mock recorder for MockIPRepository.
type MockIPRepositoryMockRecorder struct {
	mock *MockIPRepository
}

// NewMockIPRepository creates a new mock instance.
func NewMockIPRepository(ctrl *gomock.Controller) *MockIPRepository {
	mock := &MockIPRepository{ctrl: ctrl}
	mock.recorder = &MockIPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPRepository) EXPECT() *MockIPRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIPRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIPRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIPRepository)(nil).DeleteByID), ctx, id)
}

// GetAll mocks base method.
func (m *MockIPRepository) GetAll(ctx context.Context) ([]model.IPRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.IPRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIPRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIPRepository)(nil).GetAll), ctx)
}

// GetBlackList mocks base method.
func (m *MockIPRepository) GetBlackList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlackList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlackList indicates an expected call of GetBlackList.
func (mr *MockIPRepositoryMockRecorder) GetBlackList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlackList", reflect.TypeOf((*MockIPRepository)(nil).GetBlackList), ctx)
}

// GetGreylist mocks base method.
func (m *MockIPRepository) GetGreylist(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGreylist", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGreylist indicates an expected call of GetGreylist.
func (mr *MockIPRepositoryMockRecorder) GetGreylist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGreylist", reflect.TypeOf((*MockIPRepository)(nil).GetGreylist), ctx)
}

// GetWhitelist mocks base method.
func (m *MockIPRepository) GetWhitelist(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWhitelist", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWhitelist indicates an expected call of GetWhitelist.
func (mr *MockIPRepositoryMockRecorder) GetWhitelist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWhitelist", reflect.TypeOf((*MockIPRepository)(nil).GetWhitelist), ctx)
}

// InsertRule mocks base method.
func (m *MockIPRepository) InsertRule(ctx context.Context, ip, ruleType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRule", ctx, ip, ruleType)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRule indicates an expected call of InsertRule.
func (mr *MockIPRepositoryMockRecorder) InsertRule(ctx, ip, ruleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRule", reflect.TypeOf((*MockIPRepository)(nil).InsertRule), ctx, ip, ruleType)
}
